# Generated by Django 4.1.7 on 2023-07-12 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_groupchat_admin_groupchat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='participants',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='participants',
            field=models.ManyToManyField(related_name='paticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
