# Generated by Django 4.1.7 on 2023-07-12 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_groupchat_participants_groupchat_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
