# Generated by Django 4.1.7 on 2023-07-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupmessage_sender_alter_groupmessage_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
